# Questo notebook costruisce i vari csv ripulendo i dati in modo che siano pronti per essere processati

In [1]:
import json
import csv
import time
from datetime import datetime
import numpy as np
import pandas as pd
from os import listdir

types = ['profile.json', 'isee.json', 'exams.booked.json', 'exams.taken.json', 'diplomas.json']  # Lista dei file da aprire per ogni studente

vProfile = ["annoAccaCors", "annoCorso", "annoDiNascita", "cittadinanza", "codCorso", "creditiTotali", "erasmus", "facolta", "flagIdentificato", "isMedicina", "iscritto",
            "luogoDiNascita", "nazioneNascita", "primaIscr", "sesso", "tipoCorso", "tipoIscrizione", "tipoStudente", "ultIscr"]
vIsee = ["nonDichiaro", "valoreIntero"]
vBooked = ["cfuPrenotati", "ultPren"]
vTaken = ["cfuTake", "ultSup", "mediaVoto"]  # Esito -->"valoreNonNominale"
vDiplomas = ["voto", "diplomando", "codiTiso"]
DELTA = 182  # in numero di giorni, 182 = 6 mesi

######### DA CAMBIARE CON PERCORSO VERO #########################
# Vero: '/home/andrea/Scrivania/Andrea/Scuola/Triennale/Tirocinio/FullDS'
p = '../FullDS/'
N_STUDENTS = max([int(el.split('.')[0]) for el in listdir(p)]) + 1

In [2]:
N_STUDENTS

97976

### Funzioni necessarie a raggruppare i dati sparsi

In [36]:
def take_info_booked(data):
    studentInfo = []
    if data['appelli'] != []:
        totCFU = 0
        lastDate = []
        for el in data['appelli']:
            totCFU += el['crediti']
            lastDate.append(datetime.strptime(
                el['dataAppe'], '%d/%m/%Y')) if el['dataAppe'] != None else None
            # lastDate.append(datetime.strptime(el['dataAppe'], '%d/%m/%Y'))
        studentInfo.append(totCFU)
        lastDate.sort()
        studentInfo.append(int(round(lastDate[-1].timestamp()))) if lastDate != [
        ] else None
    else:
        return [0, 946684800] # Timestamp of 2000-01-01
    return studentInfo

def take_info_profile(data, v):
    v_countries = ["AUSTRIA", "BELGIO", "REPUBBLICA di BULGARIA", "REPUBBLICA di CIPRO", "CROAZIA", "DANIMARCA", "ESTONIA", "FINLANDIA", "FRANCIA", "GERMANIA",
            "REPUBBLICA FEDERALE TEDESCA", "GRECIA", "IRLANDA", "LETTONIA", "LITUANIA", "LUSSEMBURGO", "MALTA", "PAES BASSI", "POLONIA", "PORTOGALLO", "REPUBBLICA CECA",
            "ROMANIA", "SLOVACCHIA", "SLOVENIA", "SPAGNA", "SVEZIA", "UNGHERIA"]
    studentInfo = []
    if data != []:
        for el in v:
            # Cittadinanza a grana media, togliere questo if per tornare all'originale
            if el == "cittadinanza":
                if data['nazioneNascita'] == "ITALIA":
                    studentInfo.append("ITA")
                elif data['nazioneNascita'] in v_countries:
                    studentInfo.append("UE")
                else:
                    studentInfo.append("Extra-UE")
            elif el == "primaIscr" or el == "ultIscr":
                studentInfo.append(int(data[el].split('/')[0])) if data[el] != '' else studentInfo.append('None')
            else:
                studentInfo.append(data[el])
    else:
        for el in v:
            studentInfo.append('None')
    return(studentInfo)

def take_info_diplomas(data, v):
    studentInfo = []
    if data != []:
        for el in v:
            if el == 'voto' and data['lode'] == '1':
                studentInfo.append(101)
            # Scala il voto dei diplomi esteri
            elif el == 'voto' and data['baseVoto'] > '0' and data['baseVoto'] != '100':
                voto = round(
                    (float(data[el]) * 100) / int(data['baseVoto']))
                studentInfo.append(voto)
            elif el == 'voto' and data['diplomando'] != '1':
                # Gli indiani pur avendo base 100 hanno voti finali decimali
                studentInfo.append(round(float(data[el])))
            else:
                studentInfo.append(data[el])
    else:
        for el in v:
            studentInfo.append('None')
        print(studentInfo)
    return(studentInfo)

def take_info_isee(data, v):
    studentInfo = []
    if data != []:
        for el in v:
            studentInfo.append(data[el])
    else:
        for el in v:
            studentInfo.append('None')
    return studentInfo

def take_info_taken(data, v):
    studentInfo = []
    if data['esami'] != [] and data['esami'] != None:
        totCFU = 0
        lastDate = []
        grades = []
        for el in data['esami']:
            totCFU += el['cfu']
            # lastDate.append(datetime.strftime(datetime.strptime(
            #     el['data'], '%d/%m/%Y'), '%d/%m/%Y')) if el['data'] != None else None
            lastDate.append(datetime.strptime(
                el['data'], '%d/%m/%Y')) if el['data'] != None else None
            grades.append(el['esito']['valoreNonNominale']
                        ) if not el['esito']['nominale'] else None  # Se è un'idoneità considera i crediti ma non va a cercare il voto
        studentInfo.append(totCFU)
        lastDate.sort()
        # studentInfo.append(datetime.strftime(datetime.strptime(
        #     lastDate[-1], '%Y/%m/%d'), '%d/%m/%Y')) if lastDate != [
        # ] else None
        studentInfo.append(int(round(lastDate[-1].timestamp()))) if lastDate != [
        ] else None  # min prende la piu' recente
        studentInfo.append(int(np.average(grades))) if grades != [
        ] else studentInfo.append(None)
    else:
        return [0, 946684800, 0]
    return studentInfo
    
def take_info_ll(data):
    if data != '':
        return int(round(time.mktime(datetime.strptime(
            data, '%Y-%m-%dT%H:%M:%SZ').timetuple())))
    else:
        return 946684800

### Creazione del dataset a partire dai json

In [48]:
######################## INSERISCE INTESTAZIONE NEL FILE ##########################################

vTot = ['ID_Stud']
for i in [vProfile, vIsee, vBooked, vTaken, vDiplomas]:
    for el in i:
        vTot.append(el)
vTot.append("lastLogin")
# vTot.append("Dropout")
with open('assets/out.tsv', 'w') as out_file:
    writer = csv.writer(out_file, delimiter='\t')
    writer.writerow(vTot)

######################## CREA FILE CSV ############################
# Se cambia il percorso di input bisogna stare attenti sopratutto allo spit nell'except
k = 0
listRaggr = []
for student in range(0, N_STUDENTS):
    studentInfo = [student]
    for t in types:
        file_name = p + str(student) + '.' + t
        try:  # Gestisce eccezione file not found
            with open(file_name) as in_data:
                tmp = json.load(in_data)
                if file_name == (p + str(student) + '.exams.booked.json'):
                    studentInfo.append(take_info_booked(tmp.pop('ritorno')))
                elif file_name == (p + str(student) + '.isee.json'):
                   studentInfo.append(take_info_isee(tmp, vIsee))
                elif file_name == (p + str(student) + '.profile.json'):
                    studentInfo.append(take_info_profile(tmp.pop('ritorno'), vProfile))
                elif file_name == (p + str(student) + '.diplomas.json'):
                    if tmp != None:
                        studentInfo.append(take_info_diplomas(tmp[0], vDiplomas))
                    else: studentInfo.append(['None' for _ in vDiplomas])
                elif file_name == (p + str(student) + '.exams.taken.json'):
                    tmp.pop('esito')
                    studentInfo.append(take_info_taken(tmp['ritorno'], vTaken))
        except Exception as e:
            f = str(e).split('.')[3:5]
            if f == ['exams', 'booked']: studentInfo.append([0, 946684800])
            elif f == ['isee', "json'"]: studentInfo.append(['None' for _ in vIsee])
            elif f == ['profile', "json'"]: studentInfo.append(['None' for _ in vProfile])
            elif f == ['diplomas', "json'"]: studentInfo.append(['None' for _ in vDiplomas])
            elif f == ['exams', 'taken']: studentInfo.append([0, 946684800, 0])
    try:
        with open((p + str(student) + '.lastlogin.txt')) as in_data:
            studentInfo.append(take_info_ll(in_data.read()))
    except:  # Exception as e:
        studentInfo.append(946684800)

    with open('assets/out.tsv', 'a') as out_file:
        writer = csv.writer(out_file, delimiter='\t')
        tmp = [i for b in map(lambda x:[x] if not isinstance(x, list) else x, studentInfo) for i in b]
        writer.writerow(tmp)

#### Check

In [49]:
sentinels = ['None', 'n.d.', ' ', '']
df = pd.read_csv('assets/out.tsv', sep='\t', na_values=sentinels)
df.head()

,ID_Stud,annoAccaCors,annoCorso,annoDiNascita,cittadinanza,codCorso,creditiTotali,erasmus,facolta,flagIdentificato,...,valoreIntero,cfuPrenotati,ultPren,cfuTake,ultSup,mediaVoto,voto,diplomando,codiTiso,lastLogin
0,0,2022,3.0,1997,ITA,30007.0,360.0,NO,Interfacolta tra FARMACIA E MEDICINA - MEDICIN...,0,...,50058.0,0.0,946684800,32.0,1.617660e+09,22.0,99.0,0.0,2271342.0,1.643190e+09
1,1,2022,2.0,2000,UE,29950.0,180.0,NO,LETTERE E FILOSOFIA,0,...,57.0,18.0,1645052400,54.0,1.644534e+09,28.0,82.0,0.0,2274186.0,1.644601e+09
2,2,2022,4.0,1999,ITA,30009.0,360.0,NO,Interfacolta tra FARMACIA E MEDICINA - MEDICIN...,1,...,-1.0,12.0,1645398000,136.0,1.644188e+09,27.0,84.0,0.0,2179796.0,1.644442e+09
3,3,2022,2.0,1997,Extra-UE,30827.0,120.0,NO,ECONOMIA,1,...,9072.0,9.0,1613343600,9.0,1.613344e+09,26.0,72.0,0.0,2008756.0,1.644474e+09
4,4,2022,1.0,1999,ITA,30046.0,180.0,NO,"SCIENZE MATEMATICHE, FISICHE E NATURALI",1,...,-1.0,18.0,1645138800,150.0,1.643152e+09,23.0,82.0,0.0,2197799.0,1.644355e+09

In [50]:
sentinels = ['None', 'n.d.', ' ', '']
df = pd.read_csv('assets/out.tsv', sep='\t', na_values=sentinels)
df.shape

(97976, 31)

### Pulizia dati togliendo gli studenti di medicina, quelli in erasmus (incoming) e i diplomandi. Con relative colonne

In [51]:
with open('assets/cl_out.tsv', "w") as file:
    pass

with open('assets/out.tsv', mode='r') as file:
    csvFile = csv.reader(file, delimiter = '\t')
    for row in csvFile:
        # Questo if lascia passare solo i buoni # row[36] == 'None' or per diplomando
        if (row[7] == 'NO' or row[7] == 'erasmus') and (row[10] == 'False' or row[10] == 'isMedicina') and (row[29] == 'None' or row[28] == '0' or row[28] == 'diplomando') and (row[5] == 'codCorso' or row[5] != ''):
            row[9] = row[9].replace(",", " ")
            row[9] = row[9].replace("\n", " ")
            row[13] = row[13].replace(",", "-")
            row.pop(29)
            row.pop(28) #diplomando
            row.pop(10) #medicina
            row.pop(7) #erasmus
            with open('assets/cl_out.tsv', 'a') as out_file:
                writer = csv.writer(out_file, delimiter = '\t')
                writer.writerow(row)

In [52]:
sentinels = ['None', 'n.d.', ' ', '']
df = pd.read_csv('assets/cl_out.tsv', sep='\t', na_values=sentinels)
df.shape

(74851, 27)

### Etichettatura (dropout = true)

In [3]:
def diff_month(d): return abs((datetime.today() - d)).days

def supp_lab(row):
    res = True
    taken = float(row[22]) if row[22] != 'None' else 0
    booked = float(row[20]) if row[20] != 'None' else 0
    tot = float(row[6]) if row[6] != 'n.d' else 0
    if tot != 0 and (booked + taken) == tot: # Ha finito il percorso
        res = False
    elif row[21] != 'None' or row[23] != 'None': # Se ha almeno una delle due date
        # Nella riga successiva era: datetime.strptime(row[21], '%Y-%m-%d')
        d_booked = int(row[21]) if row[21] != 'None' else 946684800 # datetime.strptime('2000-01-01', '%Y-%m-%d')
        # Nella riga successiva era: datetime.strptime(row[23], '%Y-%m-%d')
        d_taken = int(row[23]) if row[23] != 'None' else 946684800 # datetime.strptime('2000-01-01', '%Y-%m-%d')
        last_date = max(d_booked, d_taken)
        if diff_month(datetime.fromtimestamp(last_date)) > DELTA:
            res = True  # Dropout
        else:
            res = False  # NON dropout
    else:
        res = True

    return res

In [4]:
with open('assets/lab_out.tsv', "w") as file:
    pass

with open('assets/cl_out.tsv', "r") as file:
    csvFile = csv.reader(file, delimiter = '\t')
    for row in csvFile:
        if row[len(row)-1] == 'lastLogin':
            row.append('Dropout')
        elif row[len(row)-1] != 'None': # Ha il login
            dll = datetime.fromtimestamp(int(row[len(row)-1]))
            if diff_month(dll) <= DELTA:
                row.append(False)  # NON Dropout
            else:
                row.append(supp_lab(row))
            # else:
            #     row.append(True)  # Dropout
        else: # Qui entra sia se non ha il login e sia se ce l'ha ma è troppo vecchio
            row.append(supp_lab(row))

        with open("assets/lab_out_182.tsv", "a") as out:
            writer = csv.writer(out, delimiter = '\t')
            writer.writerow(row)

In [5]:
sentinels = ['None', 'n.d.', ' ', '']
df = pd.read_csv('assets/lab_out_182.tsv', sep='\t', na_values=sentinels)
df.head()

,ID_Stud,annoAccaCors,annoCorso,annoDiNascita,cittadinanza,codCorso,creditiTotali,facolta,flagIdentificato,iscritto,...,nonDichiaro,valoreIntero,cfuPrenotati,ultPren,cfuTake,ultSup,mediaVoto,voto,lastLogin,Dropout
0,1,2022,2.0,2000,UE,29950,180,LETTERE E FILOSOFIA,0,SI,...,False,57.0,18.0,1645052400,54.0,1644534000,28.0,82.0,1644601030,False
1,2,2022,4.0,1999,ITA,30009,360,Interfacolta tra FARMACIA E MEDICINA - MEDICIN...,1,SI,...,True,-1.0,12.0,1645398000,136.0,1644188400,27.0,84.0,1644442067,False
2,3,2022,2.0,1997,Extra-UE,30827,120,ECONOMIA,1,SI,...,False,9072.0,9.0,1613343600,9.0,1613343600,26.0,72.0,1644473621,False
3,4,2022,1.0,1999,ITA,30046,180,"SCIENZE MATEMATICHE, FISICHE E NATURALI",1,SI,...,True,-1.0,18.0,1645138800,150.0,1643151600,23.0,82.0,1644355169,False
4,5,2022,2.0,1990,ITA,27592,120,INGEGNERIA CIVILE E INDUSTRIALE,0,NO,...,False,-2.0,0.0,946684800,111.0,1548198000,27.0,76.0,1636963837,False

In [6]:
print(df.shape)
df = df[(pd.isnull(df['annoCorso']) == False) & (df['primaIscr'] > 2000) & (df['annoDiNascita'] > 1970)]
df.to_csv('assets/lab_out_182.tsv', index = False, sep='\t')
print(df.shape)

(74851, 28)
(74281, 28)

In [7]:
v_dates = ["annoAccaCors", "annoDiNascita", "primaIscr", "ultIscr"]
df = df.astype({'annoCorso': np.int32, "primaIscr": np.int32, "ultIscr": np.int32})
for el in v_dates:
    df[el] = df[el].apply(lambda x: int(round(time.mktime(datetime.strptime(str(x), '%Y').timetuple()))))

In [8]:
val = {"SI": True, "NO": False}
df["iscritto"] = df["iscritto"].map(val)

val = {"M": True, "F": False}
df["sesso"] = df["sesso"].map(val)

val = {"true": True, "false": False}
df["nonDichiaro"] = df["nonDichiaro"].map(val)

df = df.astype({'annoCorso': np.int32, 'annoAccaCors': np.int32, 'annoDiNascita': np.int32, 'iscritto': bool, 'sesso': bool, 'primaIscr': np.int32, 'ultIscr': np.int32,
                'cfuTake': np.int32, 'cfuPrenotati': np.int32, 'lastLogin': np.int64})

In [9]:
print("Originale: ", df.shape[0])
t = df[df['codCorso'] == 29923].shape[0] # Triennale
print("Triennale", t)
m = df[df['codCorso'] == 29932].shape[0] # Magistrale
print("Magistrale: ", m)
print("Totale: ", t+m)

Originale:  74281
Triennale 803
Magistrale:  252
Totale:  1055

In [10]:
for el in [29923, 29932]:
    index_names = df[df['codCorso'] == el].index
    df.drop(index_names, inplace = True)
df.rename(columns = {'voto':'votoDiploma'}, inplace = True)
print(df.shape) # Ok 73226

(73226, 28)

In [11]:
df.loc[df.valoreIntero < 0,'valoreIntero'] = 50000
df = df.drop(['nonDichiaro'], axis=1)
index_names = df[df['mediaVoto'] > 31].index
df.drop(index_names, inplace=True)

In [12]:
df.to_csv('assets/yid_out_182.tsv', index = False, sep='\t')